#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""生成 docs/I18N-TODO.md：按文件列出待翻译的运行期中文字面量（前 N 条）。"""
import io, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent.parent
PAT = re.compile(r'"[^"\n]*[\u4e00-\u9fff][^"\n]*"')
rows = []
for p in sorted((ROOT / "autozt").glob("*.py")):
    if p.name == "i18n.py":
        continue
    txt = p.read_text(encoding="utf-8")
    hits = [h.strip('"') for h in PAT.findall(txt)]
    if hits:
        rows.append((p.name, hits))
total = sum(len(h) for _n, h in rows)
lines = ["# Runtime messages still to translate",
         "",
         "Generated by scripts/i18n_todo.py. The numbers are a lower bound of what a user",
         "sees: help text is complete, and the most visible labels, prefixes, hints and",
         "diagnostics are already wrapped or mapped (see docs/I18N.md for the mechanism).",
         "",
         "Total Chinese literals in the package: **%d**" % total,
         "",
         "## By file", "",
         "| file | count |", "|---|---|"]
for name, hits in sorted(rows, key=lambda r: -len(r[1])):
    lines.append("| %s | %d |" % (name, len(hits)))
for name, hits in sorted(rows, key=lambda r: -len(r[1]))[:6]:
    lines += ["", "## %s (first 12)" % name, ""]
    for h in hits[:12]:
        lines.append("- %s" % h.replace("|", "\\|"))
lines += ["", "## Migration procedure", "",
          "See docs/I18N.md. Do it in small batches (5-10 messages), wrap the WHOLE",
          "expression, then run: ast.parse -> az skills/schema -> pytest -> i18n_report."]
(ROOT / "docs" / "I18N-TODO.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
print("docs/I18N-TODO.md 已生成，共 %d 条中文字面量" % total)
