#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build the paper tables that describe AutoZT skills (npj Computational Materials draft).

One data source, three outputs next to this script:
    AutoZT_software_overview_npj.docx   Word tables for the manuscript / SI
    software-overview.md                Markdown copy (mkdocs, GitHub)
    software-overview.html              stand-alone HTML copy

Tables:
    Table 1   the 20 core skills, grouped by workflow stage
    Table 2   which skill supplies each quantity of zT = S^2 sigma T / (kappa_e + kappa_L)
    Table 3   agent access (MCP / Agent CLI) by risk tier
    Table S1  the 5 skills added after the 20-skill evaluation set
    Table S2  external software and the skills that use it
    Table S3  2D-specific treatments

The text is written by hand; check_repo() compares it with the repository (skill names and
versions, MCP tool counts, engine lists vs Table S2, cited paths) before anything is written.

Usage:  python3 docs/build_skill_tables.py        (needs python-docx)
"""

import datetime
import functools
import html
import re
import sys
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
OUT_DOCX = HERE / "AutoZT_software_overview_npj.docx"
OUT_MD = HERE / "software-overview.md"
OUT_HTML = HERE / "software-overview.html"

SUBTITLE = "Generated by docs/build_skill_tables.py; edit the data there and rebuild, not this file."
DOC_DATE = datetime.datetime(2026, 10, 4)  # fixed, so that the .docx properties do not change on rebuild
TEXT_WIDTH_IN = 9.7                         # landscape Letter, 0.65 in margins

# --------------------------------------------------------------------------------------
# Data. Plain Unicode; '_L', '_e', '_F', '_z' after κ / T / E / k become subscripts.
# Skill names, MCP tool names, parameters and repository paths are set in monospace.
# --------------------------------------------------------------------------------------

T1_TITLE = "Table 1 | The 20 core AutoZT skills, organised by workflow stage."
T1_HEAD = ["Skill", "zT role", "Output", "Level", "Main engines", "Hardware", "2D"]
T1_WIDTHS = [1.65, 0.75, 2.55, 0.9, 2.3, 0.85, 0.5]
# (stage, [(skill, zT role, output, level, engines, hardware, 2D), ...])
T1 = [
    ("A. Prescreening", [
        ("te-screen", "screen", "Surrogate n/p electronic ZT_e and power-factor scores (no κ_L)",
         "ML (ridge)", "NumPy", "Local", "2D only"),
    ]),
    ("B. Structure and stability", [
        ("opt-dft-cpu", "input", "Relaxed structure; total, formation and intercalation energies", "DFT",
         "VASP, VASPKIT", "CPU", "✓"),
        ("opt-mlff-cpu / opt-mlff-gpu", "input",
         "Relaxed structure and formation energy (high-throughput prescreen)", "MLIP", "MACE, ASE",
         "CPU / GPU", "✓"),
        ("phonon-dft-cpu", "check",
         "Harmonic phonon dispersion with LO–TO correction; imaginary-mode and ZA stability gate",
         "DFT + DFPT", "VASP, VASPKIT, Phonopy, SeeK-path", "CPU", "✓"),
        ("phonon-mlff-cpu / phonon-mlff-gpu", "check",
         "Harmonic phonon dispersion; imaginary-mode stability screen", "MLIP",
         "MACE, ASE, hiPhive, Phonopy (symfc)", "CPU / GPU", "✓"),
        ("elastic-dft-cpu", "check", "Elastic tensor, Born stability, moduli; Debye temperature, sound "
         "velocities and minimum κ_L estimate (3D)", "DFT", "VASP, VASPKIT, pymatgen", "CPU", "✓"),
    ]),
    ("C. Electronic structure, carriers and transport", [
        ("band-dft-cpu", "—", "Semilocal and hybrid band structures and gaps; SOC for heavy elements; "
         "vacuum-aligned band edges in 2D", "DFT", "VASP, VASPKIT, SeeK-path", "CPU", "✓"),
        ("unihamgnn", "—", "ML-predicted Hamiltonian, band structure and gap", "ML",
         "Uni-HamGNN, OpenMX tools", "CPU", "—"),
        ("ke-dft-cpu", "S, σ, κ_e", "S, σ, κ_e and mobility (n, T) with ADP, IMP and POP scattering",
         "DFT + DFPT", "VASP, VASPKIT, AMSET, BoltzTraP2", "CPU", "✓"),
        ("defect-dft-cpu", "—", "Intrinsic defect formation energies, transition levels, "
         "self-consistent E_F, n/p type", "DFT", "VASP, pymatgen, spglib", "CPU", "3D"),
        ("eph-qe-cpu", "—", "Wannier-interpolated electron–phonon matrix elements", "DFT + DFPT",
         "Quantum ESPRESSO, Wannier90, Perturbo", "CPU", "3D"),
    ]),
    ("D. Lattice transport", [
        ("kl-dft-cpu", "κ_L", "fc2/fc3, LO–TO correction, κ_L(T)", "DFT + DFPT",
         "VASP, VASPKIT, hiPhive, Phono3py (symfc / ALM); optional Pheasy, ShengBTE",
         "CPU (GPU for Pheasy)", "✓"),
        ("kl-mlff-cpu / kl-mlff-gpu", "κ_L", "fc2/fc3, κ_L(T)", "MLIP",
         "MACE, ASE, hiPhive, Phono3py (symfc); optional Pheasy, ShengBTE", "CPU / GPU", "✓"),
        ("fit-fc-thermal", "κ_L",
         "Refit fc2/fc3 from existing displacement–force data, κ_L(T), fitting-method sweep", "Fitting",
         "Pheasy, Phono3py (symfc / ALM), hiPhive; optional ShengBTE", "CPU / GPU", "✓"),
    ]),
    ("E. zT assembly", [
        ("zt-dft-cpu", "zT", "S, σ, κ_e, κ_L → zT(n, T), peak zT", "DFT + DFPT",
         "VASP, VASPKIT, AMSET, hiPhive, Phono3py", "CPU", "✓"),
    ]),
    ("F. MLIP training", [
        ("mlff", "input", "Material-specific fine-tuned MACE potential with phonon and EOS acceptance tests",
         "DFT + MLIP", "VASP, VASPKIT, MACE, hiPhive, Phonopy, ASE", "CPU / GPU", "✓†"),
    ]),
    ("G. Bonding analysis", [
        ("cohp-cogito", "—", "COHP, ICOHP and ICOBI bonding analysis", "Post-proc.",
         "COGITO (reads VASP WAVECAR)", "CPU", "—"),
    ]),
]
T1_NOTE = (
    "The 20 core skills occupy 17 rows; CPU and GPU variants share a row. zT role: S, σ, κ_e / κ_L / zT, the "
    "quantity of zT = S²σT/(κ_e + κ_L) the skill computes; input, a structure or potential that later stages "
    "use; check, a stability check; screen, a ranking before DFT; —, not part of the zT chain. Level: DFT, "
    "density-functional theory; DFPT, density-functional perturbation theory (VASP: dielectric tensor and "
    "Born charges; Quantum ESPRESSO: phonons and electron–phonon coupling); MLIP, machine-learning "
    "interatomic potential (MACE; the foundation model MACE-matpes-pbe-omat-ft by default, or a model "
    "fine-tuned by mlff); ML, other machine-learning models. Hardware: Local, login node or workstation "
    "without a batch queue. GPU variants evaluate MACE forces on the GPU; force-constant fits and Boltzmann "
    "solutions run on CPU, except Pheasy fits, which need a GPU. 2D: ✓, the skill detects a 2D slab and "
    "switches templates, relaxation constraints, units or thickness normalisation; †, implemented but not yet "
    "run on a 2D material; 2D only, trained on 2D materials only; 3D, the input is treated as bulk; —, not "
    "dimension-specific. eph-qe-cpu has so far been run only with smoke-test settings on Si. ADP, IMP, POP, "
    "acoustic-deformation-potential, ionised-impurity and polar-optical-phonon scattering; SOC, spin–orbit "
    "coupling; EOS, equation of state. Five further skills are listed in Supplementary Table S1."
)

T2_TITLE = "Table 2 | Coverage of the thermoelectric figure of merit zT = S²σT/(κ_e + κ_L)."
T2_HEAD = ["Quantity", "DFT route", "MLIP / MD route", "Cross-check", "Combined in"]
T2_WIDTHS = [0.8, 2.3, 2.2, 2.5, 1.7]
T2 = [
    ("S, σ", "ke-dft-cpu: AMSET with ADP, IMP and POP scattering", "—",
     "BoltzTraP2 with deformation-potential τ (ke-dft-cpu)", "zt-dft-cpu"),
    ("κ_e", "ke-dft-cpu: AMSET", "—", "Lorenz number, AMSET vs BoltzTraP2 (ke-dft-cpu)", "zt-dft-cpu"),
    ("κ_L", "kl-dft-cpu: fc2/fc3 + Phono3py BTE",
     "kl-mlff-cpu / kl-mlff-gpu (MACE); kl-gpumd-3090 (NEP, HNEMD; Table S1)",
     "fit-fc-thermal refits and method sweep; phonon-lifetime Ioffe–Regel check (Table S1)",
     "zt-dft-cpu (reads kl-dft-cpu or kl-mlff-* only)"),
    ("zT(n, T)", "zt-dft-cpu; ke-dft-cpu reports zT(n) at 300 K when κ_L is available",
     "zt-dft-cpu with κ_L from kl-mlff-*", "AMSET vs BoltzTraP2 zT at 300 K (ke-dft-cpu)", "—"),
]
T2_NOTE = (
    "kl-mlff-* stands for kl-mlff-cpu and kl-mlff-gpu. Inside the chain, the imaginary-mode and ZA gate of "
    "kl-dft-cpu blocks the κ_L step, and the DFPT dielectric tensor, elastic constants and deformation "
    "potentials that AMSET needs are computed within ke-dft-cpu; phonon-dft-cpu and phonon-mlff-* can be "
    "run beforehand as a stability screen. zt-dft-cpu reuses the electronic steps of ke-dft-cpu and the "
    "lattice steps of kl-dft-cpu and adds one summary step; when its own κ_L is missing it reads the "
    "kl-dft-cpu or kl-mlff-* result of the same material (a 300 K-only kl-mlff-* result restricts zT to "
    "300 K). κ_L from kl-gpumd-3090 or fit-fc-thermal is not read automatically. n is the nominal doping "
    "grid of AMSET; by default (KTEMP_MODE = interp) zT is reported only inside the κ_L temperature window, "
    "and κ_e includes the bipolar term. te-screen ranks candidates before this chain from electronic ZT_e "
    "and power factor only. BTE, Boltzmann transport equation; HNEMD, homogeneous non-equilibrium "
    "molecular dynamics."
)

T3_TITLE = "Table 3 | Agent access to AutoZT through MCP and the Agent CLI."
T3_HEAD = ["Tier", "What an agent may do", "MCP tools", "Agent CLI", "Gate"]
T3_WIDTHS = [0.85, 1.85, 2.5, 1.8, 2.5]
TOOLS_CELL = ("t3", 2)   # one-word MCP tool names ('results', 'cycle', …) are code only in this column
CLI_CELL = ("t3", 3)     # every '; '-separated item in this column is a command
T3 = [
    ("Read (19)", "Discover skills and their input/output contracts, read state and task graphs, diagnose "
     "failures, check environments, query results with units and provenance",
     "list_skills, describe_skill, schema, get_progress, get_snapshot, task_graph, inspect, probe_step, "
     "check_env, preflight, results, research_plan, …",
     "autozt agent skills; autozt agent contract; autozt agent snapshot; autozt agent inspect; "
     "autozt graph; autozt check",
     "None (read-only)"),
    ("Mutate (8)", "Register materials, set step parameters, prepare inputs, submit dependency-ready steps, "
     "pull back results",
     "register_material, conf_set, apply_actions, cycle; full profile also prepare_step, start_step, "
     "run_ready_steps, sync_results",
     "autozt register; autozt conf --set; autozt agent apply; autozt agent cycle --execute",
     "Audited; state re-checked before start/retry; stale plans rejected; per-skill max_jobs cap; "
     "force=true escalates to the destructive path"),
    ("Destructive (5)", "Cancel jobs, rebuild or clean steps, force-start",
     "request_destructive_action, approve_request; full profile also cancel_step, rebuild_step, "
     "clean_material",
     "autozt stop; autozt rerun; autozt clean; autozt start -f; autozt approve --request",
     "Approval card (command, consequence, task graph); one-time request bound to the exact command, valid "
     "900 s. Default chat mode: the agent passes on the user's reply, which is logged but cannot be verified "
     "by the server. An MCP confirmation dialog or approval_mode: tty requires the user's own client or "
     "terminal"),
]
T3_NOTE = (
    "Counts are from the tool table in autozt/mcp.py (32 tools). MCP serves LLM clients over stdio "
    "JSON-RPC; the Agent CLI gives scripts and CI the same actions through the same gateway. The default "
    "MCP profile (workflow) exposes 21 of the 32 tools; in it, inputs are prepared and steps submitted "
    "through apply_actions or cycle. AUTOZT_MCP_PROFILE=full exposes all 32."
)

S1_TITLE = "Supplementary Table S1 | AutoZT skills added after the 20-skill evaluation set."
S1_HEAD = ["Skill", "zT role", "Output", "Level", "Main engines", "Hardware", "2D", "Version and validation"]
S1_WIDTHS = [1.35, 0.6, 2.05, 0.85, 1.4, 0.95, 0.5, 1.8]
S1 = [
    ("kl-gpumd-3090", "κ_L", "κ_L by HNEMD (optional EMD Green–Kubo) with a fine-tuned NEP potential",
     "MLIP + MD", "GPUMD, NEP, ASE", "GPU (MD), CPU (NEP training)", "3D",
     "0.1; smoke-tested on Si, physics validators not yet implemented"),
    ("phonon-lifetime", "check", "Mode-resolved three-phonon lifetimes, linewidths, mean free paths; "
     "Ioffe–Regel (ωτ) overdamping flag", "Post-proc.", "Phono3py outputs, h5py, spglib", "Local", "✓",
     "0.4; reproduces the Phono3py κ of Si"),
    ("device-thermal", "—", "Device hot-spot ΔT, thermal resistance, temperature field and time constants; "
     "optional NEMD interface conductance (2D FET)", "Continuum (FVM)", "NumPy; GPUMD (optional)",
     "Local / GPU", "✓", "0.1; regression suite and FEM cross-check; NEMD conductance not converged"),
    ("device-thermal-fem", "check", "Independent steady-state FEM cross-check of device-thermal",
     "Continuum (FEM)", "scikit-fem (COMSOL interface reserved)", "Local", "—", "0.1; MoS₂ reference case"),
    ("device-zt", "—", "Joule self-heating of a 2D-FET channel (I–V, ΔT, effective temperature) and "
     "material zT at that temperature", "Continuum (FVM)", "NumPy", "Local", "✓",
     "0.1; MoS₂ and Si regression cases"),
]
S1_NOTE = (
    "Columns as in Table 1, plus version and validation status. device-thermal-fem takes its 2D-normalised "
    "inputs from device-thermal. EMD, equilibrium molecular dynamics; NEMD, non-equilibrium molecular "
    "dynamics; FVM, finite-volume method; FEM, finite-element method; FET, field-effect transistor."
)

S2_TITLE = "Supplementary Table S2 | External software used by AutoZT skills."
S2_HEAD = ["Software / package", "Role in the workflow", "Used by"]
S2_WIDTHS = [2.0, 3.2, 4.3]
S2 = [
    ("VASP", "DFT relaxations, forces, band structures, dielectric and elastic response",
     "opt-dft-cpu, phonon-dft-cpu, elastic-dft-cpu, band-dft-cpu, ke-dft-cpu, defect-dft-cpu, kl-dft-cpu, "
     "zt-dft-cpu, mlff, cohp-cogito (reads WAVECAR)"),
    ("VASPKIT", "k-mesh, k-path and POTCAR generation",
     "opt-dft-cpu, phonon-dft-cpu, elastic-dft-cpu, band-dft-cpu, ke-dft-cpu, kl-dft-cpu, zt-dft-cpu, mlff"),
    ("SeeK-path", "Band and phonon paths", "band-dft-cpu, phonon-dft-cpu"),
    ("MACE", "Machine-learning interatomic potential (foundation or fine-tuned)",
     "opt-mlff-*, phonon-mlff-*, kl-mlff-*, mlff"),
    ("ASE", "Structure handling, optimisers and calculator interface",
     "opt-mlff-*, phonon-mlff-*, kl-mlff-*, mlff, phonon-dft-cpu, fit-fc-thermal, kl-gpumd-3090"),
    ("Phonopy", "Harmonic force constants, phonon dispersions, displacement sets",
     "phonon-dft-cpu, phonon-mlff-*, kl-dft-cpu, kl-mlff-*, fit-fc-thermal, zt-dft-cpu, mlff"),
    ("Phono3py", "Anharmonic force constants and Boltzmann transport for κ_L",
     "kl-dft-cpu, kl-mlff-*, fit-fc-thermal, zt-dft-cpu, phonon-lifetime"),
    ("symfc, ALM", "Force-constant fitting back-ends of Phonopy / Phono3py",
     "phonon-mlff-*, kl-dft-cpu, kl-mlff-*, fit-fc-thermal"),
    ("hiPhive", "Monte Carlo rattled displacements; cluster-space force-constant fitting",
     "phonon-mlff-*, kl-dft-cpu, kl-mlff-*, fit-fc-thermal, zt-dft-cpu, mlff"),
    ("Pheasy (GPU build)", "Compressive-sensing force-constant fitting with Born–Huang constraints (2D)",
     "fit-fc-thermal (default), kl-dft-cpu and kl-mlff-* (optional)"),
    ("ShengBTE", "Alternative Boltzmann solver for κ_L", "kl-dft-cpu, kl-mlff-*, fit-fc-thermal (optional)"),
    ("AMSET", "Electronic transport with scattering-resolved relaxation times", "ke-dft-cpu, zt-dft-cpu"),
    ("BoltzTraP2", "Band interpolation inside AMSET; constant-relaxation-time cross-check in ke-dft-cpu",
     "ke-dft-cpu, zt-dft-cpu"),
    ("Quantum ESPRESSO, Wannier90, Perturbo", "DFPT, Wannier interpolation, electron–phonon matrix elements",
     "eph-qe-cpu"),
    ("Uni-HamGNN, OpenMX tools", "Machine-learning Hamiltonian prediction and band calculation", "unihamgnn"),
    ("COGITO", "COHP, ICOHP and ICOBI bonding analysis", "cohp-cogito"),
    ("GPUMD, NEP", "Neuroevolution potential training and molecular-dynamics thermal transport",
     "kl-gpumd-3090, device-thermal"),
    ("scikit-fem", "Finite-element device thermal model", "device-thermal-fem"),
    ("pymatgen, spglib", "Structure, symmetry, elastic-tensor and I/O utilities", "most skills"),
    ("NumPy", "Surrogate model and continuum device solvers", "te-screen, device-thermal, device-zt"),
]
S2_NOTE = "A trailing * in a skill name covers its CPU and GPU variants."

S3_TITLE = "Supplementary Table S3 | 2D-specific treatments along the workflow."
S3_HEAD = ["Treatment", "What it guards against", "Where"]
S3_WIDTHS = [3.2, 2.6, 3.7]
S3 = [
    ("Dimension detection: vacuum ≥ 8 Å along exactly one axis → 2D; the decision is passed to later steps",
     "Treating a slab as bulk", "skill/_common/opt/dim_common.py"),
    ("The 2D vacuum axis must be c; otherwise the step stops, or rotates the cell when "
     "VACUUM_AXIS_POLICY = rotate", "Misoriented slabs",
     "skill/_common/opt/relax_common.py (structure step of the VASP skills)"),
    ("In-plane-only cell relaxation (IOPTCELL / OPTCELL in VASP; cell-filter mask for MACE); k_z = 1",
     "Cell collapse along the vacuum axis",
     "skill/_common/opt/relax_common.py (VASP skills); skill/_common/mlff/mlff_relax.py (MACE skills)"),
    ("Check that the ZA branch is quadratic (ω ∝ q^p, 1.7 ≤ p ≤ 2.3)",
     "A linearised ZA branch that passes the imaginary-mode gate but corrupts κ_L",
     "skill/_common/za_2d.py; phonon-dft-cpu, phonon-mlff-*, kl-dft-cpu, kl-mlff-*, fit-fc-thermal"),
    ("Born–Huang and Huang constraints imposed in 2D force-constant fits",
     "Force constants that violate rotational invariance",
     "skill/_common/fcfit/fc_fit_driver.py; default in fit-fc-thermal (Pheasy); in kl-dft-cpu and "
     "kl-mlff-* only with FIT_ENGINE = pheasy or hiphive. Not imposed in phonon-dft-cpu (finite "
     "displacements; residual in-plane stress is checked first) or phonon-mlff-* (symfc; warns in 2D)"),
    ("Thickness normalisation of κ_L, σ and κ_e (layer thickness from the atomic span plus van der Waals "
     "radii)", "Quoting vacuum-diluted cell values as layer values",
     "skill/_common/thickness_2d.py; kl-dft-cpu, kl-mlff-*, fit-fc-thermal, phonon-lifetime; ke-dft-cpu "
     "(LAYER_THICKNESS)"),
    ("2D electronic transport: vacuum-corrected dielectric and elastic inputs; opt-in 2D scattering kernels "
     "with sheet doping in cm⁻²", "Sheet / bulk carrier-density unit mix-ups",
     "ke-dft-cpu S8; opt-in S8.4 in skill/ke-dft-cpu/step8.4_amset2d/"),
    ("zT on one cell basis (in-plane average of xx and yy)", "Mixing sheet and bulk units in zT",
     "skill/zt-dft-cpu/step20_zt/zt_common.py"),
]
S3_NOTE = "Paths are relative to the root of the AutoZT repository (version {version})."

# key, title, header, column widths (in), rows, note, rows grouped by stage
TABLES = [
    ("t1", T1_TITLE, T1_HEAD, T1_WIDTHS, T1, T1_NOTE, True),
    ("t2", T2_TITLE, T2_HEAD, T2_WIDTHS, T2, T2_NOTE, False),
    ("t3", T3_TITLE, T3_HEAD, T3_WIDTHS, T3, T3_NOTE, False),
    ("s1", S1_TITLE, S1_HEAD, S1_WIDTHS, S1, S1_NOTE, False),
    ("s2", S2_TITLE, S2_HEAD, S2_WIDTHS, S2, S2_NOTE, False),
    ("s3", S3_TITLE, S3_HEAD, S3_WIDTHS, S3, S3_NOTE, False),
]


def t1_rows():
    return [r for _, rows in T1 for r in rows]


def split_skills(cell):
    return [s.strip() for s in cell.split("/")]


def core_skills():
    return [s for r in t1_rows() for s in split_skills(r[0])]


def table_rows(rows, grouped):
    """Yield (stage or None, row) in display order; stage is set on the first row of a group."""
    for stage, srows in (rows if grouped else [(None, rows)]):
        for i, r in enumerate(srows):
            yield (stage if i == 0 else None), r


# --------------------------------------------------------------------------------------
# Inline formatting: runs(text) -> [(text, style)], style '' plain, 'c' code, 's' subscript
# --------------------------------------------------------------------------------------

PATH_RE = r"(?:skill|autozt|docs)/[\w./-]*[\w/]"
SUB_RE = re.compile(r"(?<=[κTEk])_(L|e|F|z)(?![A-Za-z])")
CODE_WORDS = {"phonon-*", "phonon-mlff-*", "kl-mlff-*", "opt-mlff-*", "approval_mode: tty", "max_jobs",
              "force=true", "AUTOZT_MCP_PROFILE=full", "LAYER_THICKNESS", "FIT_ENGINE",
              "VACUUM_AXIS_POLICY", "KTEMP_MODE"}


def tool_names():
    names = set()
    for r in T3:
        names |= {t.strip(" .…") for t in re.split(r"[,;]", r[2])}
    return {n.split()[-1] for n in names if n}   # 'full profile also prepare_step' -> 'prepare_step'


@functools.lru_cache(maxsize=None)
def identifier_re(one_word_tools):
    tools = tool_names()
    if not one_word_tools:
        tools = {t for t in tools if "_" in t}
    names = set(core_skills()) | {r[0] for r in S1} | tools | CODE_WORDS
    alt = "|".join(re.escape(n) for n in sorted(names, key=len, reverse=True))
    return re.compile(rf"(?<![\w*/-])(?:{PATH_RE}|{alt})(?![\w-])")


def runs(text, cell=None):
    out = []

    def plain(t):
        pos = 0
        for m in SUB_RE.finditer(t):
            out.extend([(t[pos:m.start()], ""), (m.group(1), "s")])
            pos = m.end()
        out.append((t[pos:], ""))

    if cell == CLI_CELL:
        for i, cmd in enumerate(text.split("; ")):
            out += [("; ", ""), (cmd, "c")] if i else [(cmd, "c")]
        return out
    pos = 0
    for m in identifier_re(cell == TOOLS_CELL).finditer(text):
        plain(text[pos:m.start()])
        out.append((m.group(0), "c"))
        pos = m.end()
    plain(text[pos:])
    return [(t, st) for t, st in out if t]


def md_cell(text, cell=None, in_table=True):
    out = []
    for t, st in runs(text, cell):
        if in_table:
            t = t.replace("|", "\\|")
        out.append(f"`{t}`" if st == "c" else f"<sub>{t}</sub>" if st == "s" else t)
    return "".join(out)


def html_cell(text, cell=None):
    tags = {"c": "code", "s": "sub"}
    return "".join(f"<{tags[st]}>{html.escape(t)}</{tags[st]}>" if st else html.escape(t)
                   for t, st in runs(text, cell))


# --------------------------------------------------------------------------------------
# Markdown
# --------------------------------------------------------------------------------------

def build_md(version):
    lines = ["# AutoZT skill tables", "", md_cell(SUBTITLE, in_table=False), ""]
    for key, title, head, _, rows, note, grouped in TABLES:
        cols = (["Stage"] + head) if grouped else head
        lines += [f"## {md_cell(title, in_table=False)}", "",
                  "| " + " | ".join(cols) + " |", "|" + "|".join([":--"] * len(cols)) + "|"]
        for stage, r in table_rows(rows, grouped):
            cells = [md_cell(c, (key, j)) for j, c in enumerate(r)]
            if grouped:
                cells.insert(0, stage or "")
            lines.append("| " + " | ".join(cells) + " |")
        lines += ["", f"*Notes:* {md_cell(note.format(version=version), in_table=False)}", ""]
    OUT_MD.write_text("\n".join(lines), encoding="utf-8")


# --------------------------------------------------------------------------------------
# HTML
# --------------------------------------------------------------------------------------

HTML_HEAD = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AutoZT skill tables</title>
  <style>
    :root { --ink:#1f2937; --muted:#5b6575; --header:#123b5d; --band:#f4f7fa; }
    * { box-sizing:border-box; }
    body { margin:0; padding:36px; color:var(--ink); background:#fff; font-family:Arial,Helvetica,sans-serif; }
    .sheet { max-width:1500px; margin:auto; }
    h1 { margin:0 0 7px; font-size:26px; color:var(--header); }
    h2 { margin:34px 0 10px; font-size:17px; color:var(--header); }
    .subtitle { margin:0 0 10px; color:var(--muted); font-size:13px; }
    .wrap { overflow-x:auto; }
    table { width:100%; border-collapse:collapse; font-size:13px; line-height:1.35;
            border-top:1.5px solid #111; border-bottom:1.5px solid #111; }
    th { padding:9px 11px; text-align:left; color:#111; font-weight:700; border-bottom:1px solid #111; }
    td { padding:7px 11px; vertical-align:top; }
    tr.stage td { font-weight:700; font-style:italic; background:var(--band); border-top:1px solid #c9d2dc; }
    code { font-family:ui-monospace,SFMono-Regular,Consolas,monospace; color:#8a3f13; font-size:12px; }
    .note { margin-top:10px; color:#4b5563; font-size:12px; }
    @media print { body { padding:0; } table { font-size:10px; } td,th { padding:5px 6px; } }
  </style>
</head>
<body>
  <main class="sheet">
    <h1>AutoZT skill tables</h1>
"""


def build_html(version):
    out = [HTML_HEAD, f'    <p class="subtitle">{html_cell(SUBTITLE)}</p>\n']
    for key, title, head, _, rows, note, grouped in TABLES:
        out.append(f'    <h2>{html_cell(title)}</h2>\n    <div class="wrap"><table>\n')
        out.append("      <thead><tr>" + "".join(f"<th>{html.escape(h)}</th>" for h in head)
                   + "</tr></thead>\n      <tbody>\n")
        for stage, r in table_rows(rows, grouped):
            if stage:
                out.append(f'        <tr class="stage"><td colspan="{len(head)}">{html.escape(stage)}</td></tr>\n')
            out.append("        <tr>" + "".join(f"<td>{html_cell(c, (key, j))}</td>" for j, c in enumerate(r))
                       + "</tr>\n")
        out.append("      </tbody>\n    </table></div>\n")
        out.append(f'    <p class="note"><strong>Notes:</strong> {html_cell(note.format(version=version))}</p>\n')
    out.append("  </main>\n</body>\n</html>\n")
    OUT_HTML.write_text("".join(out), encoding="utf-8")


# --------------------------------------------------------------------------------------
# Word: three-line tables, Times New Roman, landscape Letter
# --------------------------------------------------------------------------------------

def build_docx(version):
    from docx import Document
    from docx.enum.section import WD_ORIENT
    from docx.enum.table import WD_TABLE_ALIGNMENT
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn
    from docx.shared import Inches, Pt

    def run(p, text, size, bold=False, italic=False, style=""):
        r = p.add_run(text)
        r.bold, r.italic = bold, italic
        r.font.size = Pt(size - 0.5 if style == "c" else size)
        r.font.name = "Consolas" if style == "c" else "Times New Roman"
        r.font.subscript = True if style == "s" else None
        r._element.get_or_add_rPr().rFonts.set(qn("w:eastAsia"), "SimSun")

    def styled(p, text, size, bold=False, italic=False, cell=None):
        for t, st in runs(text, cell):
            run(p, t, size, bold, italic, st)

    def insert_ordered(parent, child, successors):
        """Insert child before the first successor present (OOXML child order is schema-checked)."""
        for name in successors:
            nxt = parent.find(qn("w:" + name))
            if nxt is not None:
                nxt.addprevious(child)
                return
        parent.append(child)

    def border_el(tag, edges):
        b = OxmlElement(tag)
        for edge, (val, sz) in edges.items():
            e = OxmlElement("w:" + edge)
            for k, v in (("val", val), ("sz", str(sz)), ("space", "0"), ("color", "000000")):
                e.set(qn("w:" + k), v)
            b.append(e)
        return b

    def fill(cell, width, text, size, bold=False, italic=False, key=None, center=False):
        cell.width = Inches(width)
        p = cell.paragraphs[0]
        p.paragraph_format.space_after = Pt(0)
        p.paragraph_format.line_spacing = 1.0
        if center:
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        styled(p, text, size, bold, italic, key)

    def paragraph(doc, space_before, space_after, page_break=False):
        p = doc.add_paragraph()
        p.paragraph_format.space_before = Pt(space_before)
        p.paragraph_format.space_after = Pt(space_after)
        p.paragraph_format.page_break_before = page_break
        return p

    doc = Document()
    props = doc.core_properties
    props.title, props.author, props.last_modified_by = "AutoZT skill tables", "AutoZT", "AutoZT"
    props.created = props.modified = DOC_DATE
    sec = doc.sections[0]
    sec.orientation = WD_ORIENT.LANDSCAPE
    sec.page_width, sec.page_height = Inches(11), Inches(8.5)
    for side in ("left_margin", "right_margin", "top_margin", "bottom_margin"):
        setattr(sec, side, Inches(0.65))
    normal = doc.styles["Normal"]
    normal.font.name = "Times New Roman"
    normal.font.size = Pt(9)
    normal.element.get_or_add_rPr().rFonts.set(qn("w:eastAsia"), "SimSun")

    size = 8.5
    for n, (key, title, head, widths, rows, note, grouped) in enumerate(TABLES):
        label, _, rest = title.partition(" | ")
        p = paragraph(doc, 4, 4, page_break=n > 0)
        run(p, label + " | ", 10.5, bold=True)
        styled(p, rest, 10.5)

        t = doc.add_table(rows=1, cols=len(head))
        t.alignment = WD_TABLE_ALIGNMENT.CENTER
        t.autofit = False
        for col, w in zip(t.columns, widths):   # w:gridCol; LibreOffice and Google Docs read these
            col.width = Inches(w)
        tblPr = t._tbl.tblPr
        insert_ordered(tblPr, border_el("w:tblBorders", {
            "top": ("single", 12), "left": ("nil", 0), "bottom": ("single", 12), "right": ("nil", 0),
            "insideH": ("nil", 0), "insideV": ("nil", 0)}),
            ("shd", "tblLayout", "tblCellMar", "tblLook", "tblCaption", "tblDescription"))
        mar = OxmlElement("w:tblCellMar")
        for side, v in (("top", 50), ("left", 70), ("bottom", 50), ("right", 70)):
            e = OxmlElement("w:" + side)
            e.set(qn("w:w"), str(v))
            e.set(qn("w:type"), "dxa")
            mar.append(e)
        insert_ordered(tblPr, mar, ("tblLook", "tblCaption", "tblDescription"))
        repeat = OxmlElement("w:tblHeader")
        repeat.set(qn("w:val"), "true")
        t.rows[0]._tr.get_or_add_trPr().append(repeat)
        twod = head.index("2D") if "2D" in head else -1

        for j, h in enumerate(head):
            c = t.rows[0].cells[j]
            fill(c, widths[j], h, size, bold=True, center=j == twod)
            insert_ordered(c._tc.get_or_add_tcPr(), border_el("w:tcBorders", {"bottom": ("single", 8)}),
                           ("shd", "noWrap", "tcMar", "textDirection", "tcFitText", "vAlign", "hideMark"))
        for stage, r in table_rows(rows, grouped):
            if stage:
                cells = t.add_row().cells
                fill(cells[0].merge(cells[-1]), sum(widths), stage, size, bold=True, italic=True)
            cells = t.add_row().cells
            for j, val in enumerate(r):
                fill(cells[j], widths[j], val, size, key=(key, j), center=j == twod)

        p = paragraph(doc, 3, 0)
        run(p, "Notes: ", 8, bold=True)
        styled(p, note.format(version=version), 8)
    doc.save(OUT_DOCX)


# --------------------------------------------------------------------------------------
# Consistency checks against the repository
# --------------------------------------------------------------------------------------

def check_repo():
    errors = []
    skills = core_skills()
    if len(skills) != 20 or len(set(skills)) != 20:
        errors.append(f"Table 1 must list 20 distinct skills, got {len(skills)}")
    if len(t1_rows()) != 17:
        errors.append(f"T1_NOTE says 17 rows, Table 1 has {len(t1_rows())}")

    on_disk = {p.parent.name for p in (REPO / "skill").glob("*/skill.yaml") if not p.parent.name.startswith("_")}
    listed = set(skills) | {r[0] for r in S1}
    if on_disk != listed:
        errors.append(f"skill/ out of sync: missing={sorted(on_disk - listed)} unknown={sorted(listed - on_disk)}")
    for r in S1:
        m = re.search(r'^version:\s*"?([\d.]+)', (REPO / "skill" / r[0] / "skill.yaml").read_text(), re.M)
        if not m or not r[-1].startswith(m.group(1) + ";"):
            errors.append(f"S1 version of {r[0]} differs from skill.yaml ({m and m.group(1)})")

    sys.path.insert(0, str(REPO))
    from autozt.mcp import TOOLS
    tiers = Counter(t[3] for t in TOOLS)
    for tier, risk in (("Read", "read"), ("Mutate", "mutate"), ("Destructive", "destructive")):
        row = next(r for r in T3 if r[0].startswith(tier))
        if row[0] != f"{tier} ({tiers[risk]})":
            errors.append(f"Table 3 says '{row[0]}', autozt/mcp.py has {tiers[risk]} {risk} tools")
    if f"({len(TOOLS)} tools)" not in T3_NOTE or f"all {len(TOOLS)}" not in T3_NOTE:
        errors.append(f"T3_NOTE tool total differs from autozt/mcp.py ({len(TOOLS)})")
    unknown_tools = tool_names() - {t[0] for t in TOOLS}
    if unknown_tools:
        errors.append(f"Table 3 names unknown MCP tools: {sorted(unknown_tools)}")

    # Every engine named in Table 1 / Table S1 must list that skill in Table S2.
    users = {}
    for names, _, used_by in S2:
        expanded = set()
        for u in re.split(r",| and ", re.sub(r"\(.*?\)", "", used_by)):
            u = u.strip()
            if u == "most skills":
                expanded |= on_disk
            elif u.endswith("*"):
                expanded |= {s for s in on_disk if s.startswith(u[:-1])}
            else:
                expanded.add(u)
        for name in re.sub(r"\(.*?\)", "", names).split(","):
            users[name.strip().lower()] = expanded
    for r in t1_rows() + S1:
        engines = re.sub(r"optional|reads|outputs|interface reserved|VASP WAVECAR", " ", r[4])
        for eng in re.split(r"[,;()/]", engines):
            eng = eng.strip().lower()
            for skill in split_skills(r[0]) if eng in users else []:
                if skill not in users[eng]:
                    errors.append(f"Table S2 '{eng}' does not list {skill}")

    for key, _, _, widths, rows, note, grouped in TABLES:
        if sum(widths) > TEXT_WIDTH_IN + 1e-9:
            errors.append(f"{key}: column widths {sum(widths):.2f} in exceed {TEXT_WIDTH_IN} in")
        for text in [note] + [c for _, r in table_rows(rows, grouped) for c in r]:
            for path in re.findall(PATH_RE, text):
                if not (REPO / path).exists():
                    errors.append(f"{key}: path does not exist: {path}")
    if errors:
        sys.exit("[ERROR] " + "\n[ERROR] ".join(errors))


def main():
    check_repo()
    version = re.search(r'^version\s*=\s*"([^"]+)"', (REPO / "pyproject.toml").read_text(), re.M).group(1)
    build_md(version)
    build_html(version)
    build_docx(version)
    for p in (OUT_DOCX, OUT_MD, OUT_HTML):
        print(p)


if __name__ == "__main__":
    main()
